"""increase_column_lengths

Revision ID: 078519919b65
Revises: 2024_03_14_02
Create Date: 2025-06-27 22:55:58.899613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '078519919b65'
down_revision = '2024_03_14_02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_request_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.ForeignKeyConstraint(['user_request_id'], ['user_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['email'])

    with op.batch_alter_table('user_request', schema=None) as batch_op:
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('user_restaurant_preference', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('_user_restaurant_uc'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_restaurant_preference', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('_user_restaurant_uc'), ['user_id', 'restaurant_id'])

    with op.batch_alter_table('user_request', schema=None) as batch_op:
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('name',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    op.drop_table('recommendation')
    # ### end Alembic commands ###
