"""Add UserRestaurantPreference table

Revision ID: 207764f037c8
Revises: bd56da29c097
Create Date: 2024-11-30 15:41:33.055412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207764f037c8'
down_revision = 'bd56da29c097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_restaurant_preference',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('preference', sa.Enum('like', 'dislike', 'neutral', name='preferencetype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'restaurant_id', name='_user_restaurant_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_restaurant_preference')
    # ### end Alembic commands ###
