"""Make location required in Restaurant table

Revision ID: 4f8f58c5ad29
Revises: 1f36bc477698
Create Date: 2024-11-30 13:17:04.391632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8f58c5ad29'
down_revision = '1f36bc477698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_request', schema=None) as batch_op:
        batch_op.alter_column('recommended_restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('request_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_id', sa.INTEGER(), nullable=False))
        batch_op.alter_column('recommended_restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
